name: Deploy to AWS Lambda

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy to Lambda
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        region: ["us-east-1", "eu-west-1", "ap-southeast-1"] # Add or remove regions as needed

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ matrix.region }}

      - name: Package Lambda Function
        run: |
          zip -r function.zip .

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name shubhamtest1 --zip-file fileb://function.zip --publish
